/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as PhasescardRouteImport } from './routes/phasescard'
import { Route as PhasesRouteImport } from './routes/phases'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhasescardIndexRouteImport } from './routes/phasescard/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as PhasescardCustomRouteImport } from './routes/phasescard/custom'
import { Route as PhasescardPhaseSetIdRouteImport } from './routes/phasescard/$phaseSetId'
import { Route as GameGameIdRouteImport } from './routes/game/$gameId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const PhasescardRoute = PhasescardRouteImport.update({
  id: '/phasescard',
  path: '/phasescard',
  getParentRoute: () => rootRouteImport,
} as any)
const PhasesRoute = PhasesRouteImport.update({
  id: '/phases',
  path: '/phases',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhasescardIndexRoute = PhasescardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PhasescardRoute,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateRoute,
} as any)
const PhasescardCustomRoute = PhasescardCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => PhasescardRoute,
} as any)
const PhasescardPhaseSetIdRoute = PhasescardPhaseSetIdRouteImport.update({
  id: '/$phaseSetId',
  path: '/$phaseSetId',
  getParentRoute: () => PhasescardRoute,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/phases': typeof PhasesRoute
  '/phasescard': typeof PhasescardRouteWithChildren
  '/players': typeof PlayersRoute
  '/settings': typeof SettingsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/phasescard/$phaseSetId': typeof PhasescardPhaseSetIdRoute
  '/phasescard/custom': typeof PhasescardCustomRoute
  '/create/': typeof CreateIndexRoute
  '/phasescard/': typeof PhasescardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/phases': typeof PhasesRoute
  '/players': typeof PlayersRoute
  '/settings': typeof SettingsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/phasescard/$phaseSetId': typeof PhasescardPhaseSetIdRoute
  '/phasescard/custom': typeof PhasescardCustomRoute
  '/create': typeof CreateIndexRoute
  '/phasescard': typeof PhasescardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/phases': typeof PhasesRoute
  '/phasescard': typeof PhasescardRouteWithChildren
  '/players': typeof PlayersRoute
  '/settings': typeof SettingsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/phasescard/$phaseSetId': typeof PhasescardPhaseSetIdRoute
  '/phasescard/custom': typeof PhasescardCustomRoute
  '/create/': typeof CreateIndexRoute
  '/phasescard/': typeof PhasescardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/phases'
    | '/phasescard'
    | '/players'
    | '/settings'
    | '/game/$gameId'
    | '/phasescard/$phaseSetId'
    | '/phasescard/custom'
    | '/create/'
    | '/phasescard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/phases'
    | '/players'
    | '/settings'
    | '/game/$gameId'
    | '/phasescard/$phaseSetId'
    | '/phasescard/custom'
    | '/create'
    | '/phasescard'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/phases'
    | '/phasescard'
    | '/players'
    | '/settings'
    | '/game/$gameId'
    | '/phasescard/$phaseSetId'
    | '/phasescard/custom'
    | '/create/'
    | '/phasescard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRouteWithChildren
  PhasesRoute: typeof PhasesRoute
  PhasescardRoute: typeof PhasescardRouteWithChildren
  PlayersRoute: typeof PlayersRoute
  SettingsRoute: typeof SettingsRoute
  GameGameIdRoute: typeof GameGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phasescard': {
      id: '/phasescard'
      path: '/phasescard'
      fullPath: '/phasescard'
      preLoaderRoute: typeof PhasescardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phases': {
      id: '/phases'
      path: '/phases'
      fullPath: '/phases'
      preLoaderRoute: typeof PhasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phasescard/': {
      id: '/phasescard/'
      path: '/'
      fullPath: '/phasescard/'
      preLoaderRoute: typeof PhasescardIndexRouteImport
      parentRoute: typeof PhasescardRoute
    }
    '/create/': {
      id: '/create/'
      path: '/'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof CreateRoute
    }
    '/phasescard/custom': {
      id: '/phasescard/custom'
      path: '/custom'
      fullPath: '/phasescard/custom'
      preLoaderRoute: typeof PhasescardCustomRouteImport
      parentRoute: typeof PhasescardRoute
    }
    '/phasescard/$phaseSetId': {
      id: '/phasescard/$phaseSetId'
      path: '/$phaseSetId'
      fullPath: '/phasescard/$phaseSetId'
      preLoaderRoute: typeof PhasescardPhaseSetIdRouteImport
      parentRoute: typeof PhasescardRoute
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CreateRouteChildren {
  CreateIndexRoute: typeof CreateIndexRoute
}

const CreateRouteChildren: CreateRouteChildren = {
  CreateIndexRoute: CreateIndexRoute,
}

const CreateRouteWithChildren =
  CreateRoute._addFileChildren(CreateRouteChildren)

interface PhasescardRouteChildren {
  PhasescardPhaseSetIdRoute: typeof PhasescardPhaseSetIdRoute
  PhasescardCustomRoute: typeof PhasescardCustomRoute
  PhasescardIndexRoute: typeof PhasescardIndexRoute
}

const PhasescardRouteChildren: PhasescardRouteChildren = {
  PhasescardPhaseSetIdRoute: PhasescardPhaseSetIdRoute,
  PhasescardCustomRoute: PhasescardCustomRoute,
  PhasescardIndexRoute: PhasescardIndexRoute,
}

const PhasescardRouteWithChildren = PhasescardRoute._addFileChildren(
  PhasescardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRouteWithChildren,
  PhasesRoute: PhasesRoute,
  PhasescardRoute: PhasescardRouteWithChildren,
  PlayersRoute: PlayersRoute,
  SettingsRoute: SettingsRoute,
  GameGameIdRoute: GameGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
