/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as CreateSummaryRouteImport } from './routes/create/summary'
import { Route as CreatePlayersRouteImport } from './routes/create/players'
import { Route as CreatePhasesRouteImport } from './routes/create/phases'

const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateRoute,
} as any)
const CreateSummaryRoute = CreateSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => CreateRoute,
} as any)
const CreatePlayersRoute = CreatePlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => CreateRoute,
} as any)
const CreatePhasesRoute = CreatePhasesRouteImport.update({
  id: '/phases',
  path: '/phases',
  getParentRoute: () => CreateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/create/phases': typeof CreatePhasesRoute
  '/create/players': typeof CreatePlayersRoute
  '/create/summary': typeof CreateSummaryRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create/phases': typeof CreatePhasesRoute
  '/create/players': typeof CreatePlayersRoute
  '/create/summary': typeof CreateSummaryRoute
  '/create': typeof CreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/create/phases': typeof CreatePhasesRoute
  '/create/players': typeof CreatePlayersRoute
  '/create/summary': typeof CreateSummaryRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/create/phases'
    | '/create/players'
    | '/create/summary'
    | '/create/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create/phases' | '/create/players' | '/create/summary' | '/create'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/create/phases'
    | '/create/players'
    | '/create/summary'
    | '/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/summary': {
      id: '/create/summary'
      path: '/summary'
      fullPath: '/create/summary'
      preLoaderRoute: typeof CreateSummaryRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/players': {
      id: '/create/players'
      path: '/players'
      fullPath: '/create/players'
      preLoaderRoute: typeof CreatePlayersRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/phases': {
      id: '/create/phases'
      path: '/phases'
      fullPath: '/create/phases'
      preLoaderRoute: typeof CreatePhasesRouteImport
      parentRoute: typeof CreateRoute
    }
  }
}

interface CreateRouteChildren {
  CreatePhasesRoute: typeof CreatePhasesRoute
  CreatePlayersRoute: typeof CreatePlayersRoute
  CreateSummaryRoute: typeof CreateSummaryRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

const CreateRouteChildren: CreateRouteChildren = {
  CreatePhasesRoute: CreatePhasesRoute,
  CreatePlayersRoute: CreatePlayersRoute,
  CreateSummaryRoute: CreateSummaryRoute,
  CreateIndexRoute: CreateIndexRoute,
}

const CreateRouteWithChildren =
  CreateRoute._addFileChildren(CreateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
